export default {
  AppLogo: require('../assets/Images/AppLogo.png'),
  loginBack: require('../assets/Images/loginBack.png'),
  eyeClosed: require('../assets/Images/eyeClosed.png'),
  eyeOpen: require('../assets/Images/EyeIcon.png'),
  lock: require('../assets/Images/lock.png'),
  User: require('../assets/Images/User.png'),
  mobile_icon: require('../assets/Images/mobile_icon.png'),
  arrowLeftBlack: require('../assets/Images/arrow-left(non-optimized).png'),
  otp_pencil: require('../assets/Images/otp_pencil.png'),
  headerImage: require('../assets/Images/headerImage.jpg'),
  back: require('../assets/Images/back.png'),
  bell_icon: require('../assets/Images/bell_icon.png'),
  searchIcon: require('../assets/Images/ic_search_search.png'),
  Home: require('../assets/Images/home.png'),
  circle: require('../assets/Images/circle.png'),
  ellipse: require('../assets/Images/ellipse.png'),
  calendar: require('../assets/Images/calendar.png'),
  ellipse1: require('../assets/Images/ellipse1.png'),
  ellipse3: require('../assets/Images/ellipse3.png'),
};
